services:
  postgres:
    image: "postgres:17"
    restart: unless-stopped
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432"
    networks:
      app_network:
        ipv4_address: 172.20.0.20

  calibrator-manager:
    image: "docker.io/christiand9699/calibrator-manager:latest"
    restart: unless-stopped
    depends_on:
      - postgres
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/CALIBRATOR"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OS: "raspberrypi"
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.15

  sensor-manager:
    image: "docker.io/christiand9699/sensor-manager:latest"
    restart: unless-stopped
    depends_on:
      - postgres
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OS: "raspberrypi"
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.10

  mongodb:
    image: mongo:4.4.18
    restart: unless-stopped
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
    ports:
      - "27017:27017"
    networks:
      app_network:
        ipv4_address: 172.20.0.23
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  measure-manager:
    image: "docker.io/christiand9699/measure:latest"
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      OS: raspberrypi
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.11

  keycloak-db:
    image: "postgres:17"
    restart: unless-stopped
    profiles:
      - keycloak-internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB_KEYCLOAK}
      POSTGRES_USER: ${POSTGRES_USER_KEYCLOAK}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      app_network:
        ipv4_address: 172.20.0.21

  keycloak:
    image: keycloak/keycloak:26.4.2
    profiles:
      - keycloak-internal
    depends_on:
      - keycloak-db
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB_KEYCLOAK}
      KC_DB_USERNAME: ${POSTGRES_USER_KEYCLOAK}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK}

      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"

    command: >
      start-dev

    ports:
      - "8081:8080"

    networks:
      app_network:
        ipv4_address: 172.20.0.22

  grafana:
    image: grafana/grafana-enterprise
    profiles:
      - grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - /var/lib/grafana/plugins
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.christiandellisanti.uk
      - GF_SERVER_DOMAIN=grafana.christiandellisanti.uk
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      #- GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_ALLOW_EMBEDDING=true

      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.christiandellisanti.uk/realms/measurestream/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.christiandellisanti.uk/realms/measurestream/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.christiandellisanti.uk/realms/measurestream/protocol/openid-connect/userinfo
      - GF_AUTH_GENERIC_OAUTH_LOGOUT_URL=https://auth.christiandellisanti.uk/realms/measurestream/protocol/openid-connect/logout?redirect_uri=https://grafana.christiandellisanti.uk
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_AUTH_GENERIC_OAUTH_USE_PKCE=true
      - GF_AUTH_GENERIC_OAUTH_USERNAME_PATH=preferred_username # O 'sub' o l'attributo che Keycloak usa come username
      - GF_AUTH_GENERIC_OAUTH_EMAIL_PATH=email
      - GF_AUTH_GENERIC_OAUTH_NAME_PATH=name

    networks:
      app_network:
        ipv4_address: 172.20.0.30

  frontend:
    image: "docker.io/christiand9699/frontend-react:latest"
    restart: unless-stopped
    ports:
      - "5173:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    #environment:
    #  NODE_ENV: development
    #stdin_open: true
    #tty: true
    #command: ["npm", "run", "dev", "--", "--host"]
    networks:
      app_network:
        ipv4_address: 172.20.0.12

  gateway-iam:
    image: "docker.io/christiand9699/gateway-iam:latest"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_GATEWAY_CLIENT_SECRET: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
      OS: "dev"
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/me"]
      interval: 10s # Ogni 10 secondi
      timeout: 5s # Timeout di 5 secondi per la risposta
      retries: 5 # Prova fino a 5 volte prima di fallire
      start_period: 120s

  kafka:
    image: bitnamilegacy/kafka:3.8.0
    hostname: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:29092,CONTROLLER://:9093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://100.78.181.75:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_HEAP_OPTS=-Xms256m -Xmx512m
    networks:
      app_network:
        ipv4_address: 172.20.0.40

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.3.2
    container_name: kafka-connect
    profiles:
      - kafka-external
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.converters.ByteArrayConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR"
    volumes:
      - ./connect-plugins:/usr/share/confluent-hub-components
    networks:
      app_network:
        ipv4_address: 172.20.0.41

  kafkastream:
    image: "docker.io/christiand9699/kafkastream:latest"
    restart: unless-stopped
    profiles:
      - kafka-external
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_APPLICATION_NAME: kafka-stream
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    depends_on:
      - kafka
    networks:
      app_network:
        ipv4_address: 172.20.0.51

  settings:
    image: "docker.io/christiand9699/settings:latest"
    restart: unless-stopped
    expose:
      - 8080
    environment:
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_CLIENT: ${MQTT_CLIENT}
      MQTT_BROKER: ${MQTT_BROKER}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/SETTINGS
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.13

volumes:
  postgres-data:
  keycloak-db-data:
  mongo_data:
  grafana_data:
  kafka_data:

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
